INSERT INTO questions (question_id, topic, difficulty, question)
VALUES
    (1, 'math', 2, 'What is the square root of 16?'),
    (2, 'history', 2, 'When alexander the great was born(only year)'),
    (3, 'science', 4, 'What is the chemical symbol for gold?'),
    (4, 'geography', 2, 'What is the capital city of Estonia?'),
    (6, 'music', 1, 'Who was lead vocalist of the rock band Queen?'),
    (7, 'sports', 5, 'How many players in one basketball team according to NBA regulations'),
    (8, 'art', 3, 'Who painted the Mona Lisa?'),
    (9, 'technology', 4, 'What does CPU stand for?'),
    (10, 'movies', 2, 'Who directed the film "The Shawshank Redemption"?'),
    (11, 'math', 0, '2+2*2 =?'),
    (12, 'math', 0, '1+1+1*(1+1) =?');

INSERT INTO responses (question_id, response_text, is_correct)
VALUES
    (1, '4', 1),
    (1, '8', 0),
    (1, '2', 0),
    (2, '356 BC', 1),
    (2, '324 AD', 0),
    (2, '502 BC', 0),
    (3, 'Au', 1),
    (3, 'Ag', 0),
    (3, 'Cu', 0),
    (4, 'Tallinn', 1),
    (4, 'Riga', 0),
    (4, 'Vilnius', 0),
    (6, 'Freddie Mercury', 1),
    (6, 'Roger Taylor', 0),
    (6, 'Brian May', 0),
    (7, '5', 1),
    (7, '6', 0),
    (7, '7', 0),
    (8, 'Leonardo da Vinci', 1),
    (8, 'Pablo Picasso', 0),
    (8, 'Vincent van Gogh', 0),
    (9, 'Central Processing Unit', 1),
    (9, 'Computer Personal Unit', 0),
    (9, 'Central Power Unit', 0),
    (10, 'Frank Darabont', 1),
    (10, 'Steven Spielberg', 0),
    (10, 'Christopher Nolan', 0),
    (11, '12', 0),
    (11, '4', 0),
    (11, '6', 1),
    (12, '11', 0),
    (12, '6', 0),
    (12, '4', 1);